sonar.projectKey=phuchuy242_FoodieGo
sonar.organization=phuchuy242

# Paths to source directories
sonar.sources=backend/apps, frontend/admin/src, frontend/emenu

# Exclusions
sonar.exclusions=**/tests.py, **/test_*.py, **/migrations/**, **/node_modules/**, **/dist/**, **/build/**, **/*.css, **/*.html

# Test coverage reporting
sonar.python.coverage.reportPaths=backend/coverage.xml
