# Generated by Django 5.2.10 on 2026-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('shipper', 'Shipper'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
