# Generated by Django 5.2.10 on 2026-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('cooking', 'Cooking'), ('ready', 'Ready for Pickup'), ('delivering', 'Delivering'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
